using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using System;

[Serializable]
public class Pzl_StageParamsEntity
{
    public int StageNo;
    public int posX;
    public int posY;
    public float scale;
    public string booktype;
    public int needCash;
    public int UpSpeed;
    public int UpRate;
    public string ResultTip0;
    public string ResultTip0_Detail;
    public int ResultTip0_Num;
    public string ResultTip1;
    public string ResultTip1_Detail;
    public int ResultTip1_Num;
    public string ResultTip2;
    public string ResultTip2_Detail;
    public int ResultTip2_Num;
    public string TipSort;
    public int TipStartNum;
    public string Start0;
    public string Start1;
    public string Start2;
    public string Start3;
    public string Start4;
    public string Start5;
    public string Start6;
    public string Start7;
    public string Start8;
    public string Start9;
    public string Start10;
    public string Start11;
    public string Start12;
    public string Start13;
    public string Start14;
    public string Start15;
    public string Start16;
    public string Start17;
    public string Start18;
    public string Start19;
    public string Start20;
    public string Start21;
    public string Start22;
    public string Start23;
    public string Start24;
    public string Start25;
    public string Start26;
    public string Start27;
    public string Start28;
    public string Start29;
    public string Start30;
    public int CareerSpeed;
    public int RundumNum;
    public int CurrentNum;
    public int MustStTip;
    public string Tip0;
    public string Tip1;
    public string Tip2;
    public string Tip3;
    public string Tip4;
    public string Tip5;
    public string Tip6;
    public string Tip7;
    public string Tip8;
    public string Tip9;
    public string Tip10;
    public string Tip11;
    public string Tip12;
    public string Tip13;
    public string Tip14;
    public string Tip15;
    public string Tip16;
    public string Tip17;
    public string Tip18;
    public string Tip19;
    public string Tip20;


}
